package addressBook;

/*
*	To change this license header, choose License Headers in Project Properties.
*	To change this template file, choose Tools | Templates
*	and open the template in the editor.
*/

import java.io.FileWriter; import java.io.IOException; import java.io.PrintWriter;

/**
*
*	@author User
*/
public class AddressBook extends javax.swing.JFrame {

/**
*	Creates new form AddressBook
*/
public AddressBook() { initComponents();
}

/**
*	This method is called from within the constructor to initialize the form.
*	WARNING: Do NOT modify this code. The content of this method is always
*	regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

jLabel5 = new javax.swing.JLabel(); name_txtField = new javax.swing.JTextField(); jLabel1 = new javax.swing.JLabel();
jLabel2 = new javax.swing.JLabel(); phn_txtField = new javax.swing.JTextField(); email_txtfld = new javax.swing.JTextField(); jLabel3 = new javax.swing.JLabel(); adrs_txtField = new javax.swing.JTextField(); jLabel4 = new javax.swing.JLabel();
search = new javax.swing.JButton(); user_info = new javax.swing.JButton(); edit = new javax.swing.JButton();
save = new javax.swing.JButton(); display = new javax.swing.JTextField(); clear = new javax.swing.JButton();

jLabel5.setText("jLabel5");
 
setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); setTitle("ADDRESSBOOK");
setLocation(new java.awt.Point(500, 250)); setResizable(false);

name_txtField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); jLabel1.setText("Name : ");

jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); jLabel2.setText(" Cell Nember: ");

phn_txtField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

email_txtfld.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); jLabel3.setText("E-mail : ");

adrs_txtField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); jLabel4.setText("Address : ");

search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
search.setText("Search");
search.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) {
searchActionPerformed(evt);
}
});

user_info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
user_info.setText("USER INFO");
user_info.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) {
user_infoActionPerformed(evt);
}
});

edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
edit.setText("Edit");
edit.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) {
editActionPerformed(evt);
}
});

save.setText("save");
 
save.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) {
saveActionPerformed(evt);
}
});

display.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
display.setHorizontalAlignment(javax.swing.JTextField.CENTER);

clear.setText("clear");
clear.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) {
clearActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane()); getContentPane().setLayout(layout);
layout.setHorizontalGroup( layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addGroup(layout.createSequentialGroup()

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(21, 21, 21)

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel3)
.addComponent(jLabel4)))
.addGroup(layout.createSequentialGroup()
.addGap(48, 48, 48)
.addComponent(search)))
.addGap(10, 10, 10)

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(phn_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(email_txtfld)
.addComponent(adrs_txtField)
.addComponent(name_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGap(0, 68, Short.MAX_VALUE))
.addGroup(layout.createSequentialGroup()

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(clear)
.addGroup(layout.createSequentialGroup()
.addGap(127, 127, 127)
 
.addComponent(user_info)))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(save)
.addComponent(edit)))))
.addGroup(layout.createSequentialGroup()

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(21, 21, 21)
.addComponent(jLabel1))
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addComponent(jLabel2)))
.addGap(0, 0, Short.MAX_VALUE)))
.addGap(21, 21, 21))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addGap(0, 0, Short.MAX_VALUE)
.addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(79, 79, 79))
);
layout.setVerticalGroup( layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(28, 28, 28)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(name_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel1))
.addGap(28, 28, 28)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(phn_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(28, 28, 28)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(email_txtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel3))
.addGap(28, 28, 28)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(adrs_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel4))
.addGap(34, 34, 34)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(save)
.addComponent(clear))
.addGap(18, 18, 18)
.addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(search)
.addComponent(user_info)
.addComponent(edit))
.addContainerGap())
);

pack();
}// </editor-fold>

private void searchActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
this.dispose();
new serc().setVisible(true);

}

private void user_infoActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:


this.dispose();
new UserInfo().setVisible(true);

}

private void editActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
this.dispose();
new EditInfo().setVisible(true);
}

private void saveActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
// System.out.println("saved");

String s1 = name_txtField.getText(); String s2 = phn_txtField.getText(); String s3 = email_txtfld.getText(); String s4 = adrs_txtField.getText();

//display.setText("Name : "+s1+"Phone Number : "+s2 +
// "Email : "+ s3+"\n"+ "Adress : "+s4);

String info = s1+ "\n" + s2+ "\n" +s3+ "\n" +s4; display.setText(info);

try{
FileWriter file = new FileWriter("saved.txt",true);
PrintWriter out = new PrintWriter(file); // java.io.FileNotFoundException

out.println(info);
 
out.close();
}
catch (IOException e){ e.printStackTrace();
}




}

private void clearActionPerformed(java.awt.event.ActionEvent evt) {

// System.out.println("vbvbvvv");
// TODO add your handling code here:

name_txtField.setText(" "); phn_txtField.setText(" "); email_txtfld.setText(" "); adrs_txtField.setText(" ");
}

/**
*	@param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
{
if ("Nimbus".equals(info.getName())) { javax.swing.UIManager.setLookAndFeel(info.getClassName()); break;
}
}
} catch (ClassNotFoundException ex) { java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE,
null, ex);
} catch (InstantiationException ex) { java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE,
null, ex);
} catch (IllegalAccessException ex) { java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE,
null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) { java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE,
null, ex);
}
//</editor-fold>

/* Create and display the form */
 
java.awt.EventQueue.invokeLater(new Runnable() { public void run() {
new AddressBook().setVisible(true);
}
});
}

// Variables declaration - do not modify private javax.swing.JTextField adrs_txtField; private javax.swing.JButton clear;
private javax.swing.JTextField display; private javax.swing.JButton edit;
private javax.swing.JTextField email_txtfld; private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2; private javax.swing.JLabel jLabel3; private javax.swing.JLabel jLabel4; private javax.swing.JLabel jLabel5;
private javax.swing.JTextField name_txtField; private javax.swing.JTextField phn_txtField; private javax.swing.JButton save;
private javax.swing.JButton search; private javax.swing.JButton user_info;
// End of variables declaration
}

package addressBook;

import java.io.BufferedReader; import java.io.FileReader; import java.io.IOException;

/*
*	To change this license header, choose License Headers in Project Properties.
*	To change this template file, choose Tools | Templates
*	and open the template in the editor.
*/

/**
*
*	@author User
*/
public class UserInfo extends javax.swing.JFrame {

/**
*	Creates new form userInfo
*/
public UserInfo() { initComponents();
}

/**
*	This method is called from within the constructor to initialize the form.
*	WARNING: Do NOT modify this code. The content of this method is always
*	regenerated by the Form Editor.
 
*/
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

show = new javax.swing.JButton(); jScrollPane1 = new javax.swing.JScrollPane(); info_box = new javax.swing.JTextArea();
setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); show.setText("Show ");
show.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) {
showActionPerformed(evt);
}
});

info_box.setEditable(false); info_box.setColumns(20); info_box.setRows(5);
info_box.addAncestorListener(new javax.swing.event.AncestorListener() { public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
}
public void ancestorAdded(javax.swing.event.AncestorEvent evt) { info_boxAncestorAdded(evt);
}
public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
}
});
jScrollPane1.setViewportView(info_box);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane()); getContentPane().setLayout(layout);
layout.setHorizontalGroup( layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(40, 40, 40)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createSequentialGroup()
.addGap(177, 177, 177)
.addComponent(show)))
.addContainerGap(47, Short.MAX_VALUE))
);
layout.setVerticalGroup( layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(24, 24, 24)
.addComponent(show)
.addGap(18, 18, 18)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
 
.addContainerGap(25, Short.MAX_VALUE))
);

pack();
}// </editor-fold>

private void showActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:

try {
FileReader fw = new FileReader("saved.txt"); BufferedReader reader = new BufferedReader(fw);

String line;
while( (line = reader.readLine()) != null){ info_box.append(line);
}

reader.close();
}
catch (IOException e){ e.printStackTrace();
}
}

private void info_boxAncestorAdded(javax.swing.event.AncestorEvent evt) {
// TODO add your handling code here:
}

/**
*	@param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
*	For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
{
if ("Nimbus".equals(info.getName())) { javax.swing.UIManager.setLookAndFeel(info.getClassName()); break;
}
}
 


ex);


ex);


ex);
 
} catch (ClassNotFoundException ex) { java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null,

} catch (InstantiationException ex) { java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null,

} catch (IllegalAccessException ex) { java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null,
 


ex);
 
} catch (javax.swing.UnsupportedLookAndFeelException ex) { java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null,
 
}
//</editor-fold>

/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() { public void run() {
new UserInfo().setVisible(true);
}
});
}

// Variables declaration - do not modify private javax.swing.JTextArea info_box; private javax.swing.JScrollPane jScrollPane1; private javax.swing.JButton show;
// End of variables declaration
}

package addressBook;
/*
*	To change this license header, choose License Headers in Project Properties.
*	To change this template file, choose Tools | Templates
*	and open the template in the editor.
*/

/**
*
*	@author User
*/
public class EditInfo extends javax.swing.JFrame {

/**
*	Creates new form EditInfo
*/
public EditInfo() { initComponents();
}

/**
*	This method is called from within the constructor to initialize the form.
*	WARNING: Do NOT modify this code. The content of this method is always
*	regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

edit_name = new javax.swing.JTextField(); jLabel1 = new javax.swing.JLabel(); jLabel2 = new javax.swing.JLabel(); edit_phn = new javax.swing.JTextField(); edit_email = new javax.swing.JTextField();
 
jLabel3 = new javax.swing.JLabel(); edit_adrs = new javax.swing.JTextField(); jLabel4 = new javax.swing.JLabel(); jLabel5 = new javax.swing.JLabel();
okay = new javax.swing.JButton(); setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); edit_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); jLabel1.setText("Name : ");

jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); jLabel2.setText(" Cell Nember: ");

edit_phn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

edit_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); jLabel3.setText("E-mail : ");

edit_adrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); jLabel4.setText("Address : ");
jLabel5.setText("Edit informtion."); okay.setText("Ok");
okay.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) {
okayActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane()); getContentPane().setLayout(layout);
layout.setHorizontalGroup( layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addGroup(layout.createSequentialGroup()
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(okay))
.addGroup(layout.createSequentialGroup()
.addGap(38, 38, 38)

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addGroup(layout.createSequentialGroup()
 
.addGap(11, 11, 11)

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel3)
.addComponent(jLabel4))
.addGap(47, 47, 47)

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(edit_email)
.addComponent(edit_adrs, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(layout.createSequentialGroup()

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(11, 11, 11)
.addComponent(jLabel1))
.addComponent(jLabel2)
.addComponent(jLabel5))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(edit_name)
.addComponent(edit_phn, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))))
.addGap(46, 46, 46))
);
layout.setVerticalGroup( layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(19, 19, 19)
.addComponent(jLabel5)
.addGap(63, 63, 63)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(edit_name, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel1))
.addGap(28, 28, 28)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(edit_phn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(28, 28, 28)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(edit_email, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel3))
.addGap(28, 28, 28)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(edit_adrs, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel4))
.addGap(51, 51, 51)
 
.addComponent(okay)
.addContainerGap(54, Short.MAX_VALUE))
);

pack();
}// </editor-fold>

private void okayActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

/**
*	@param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
*	For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
{
if ("Nimbus".equals(info.getName())) { javax.swing.UIManager.setLookAndFeel(info.getClassName()); break;
}
}
 


ex);


ex);


ex);


ex);
 
} catch (ClassNotFoundException ex) { java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null,

} catch (InstantiationException ex) { java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null,

} catch (IllegalAccessException ex) { java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null,

} catch (javax.swing.UnsupportedLookAndFeelException ex) { java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null,
 
}
//</editor-fold>

/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() { public void run() {
new EditInfo().setVisible(true);
}
});
}

// Variables declaration - do not modify private javax.swing.JTextField edit_adrs; private javax.swing.JTextField edit_email; private javax.swing.JTextField edit_name;
 
private javax.swing.JTextField edit_phn; private javax.swing.JLabel jLabel1; private javax.swing.JLabel jLabel2; private javax.swing.JLabel jLabel3; private javax.swing.JLabel jLabel4; private javax.swing.JLabel jLabel5; private javax.swing.JButton okay;
// End of variables declaration
}
package addressBook;

/*
*	To change this license header, choose License Headers in Project Properties.
*	To change this template file, choose Tools | Templates
*	and open the template in the editor.
*/

/**
*
*	@author User
*/
public class serc extends javax.swing.JFrame {

/**
*	Creates new form serc
*/
public serc() { initComponents();
}

/**
*	This method is called from within the constructor to initialize the form.
*	WARNING: Do NOT modify this code. The content of this method is always
*	regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

src_name = new javax.swing.JTextField(); jLabel1 = new javax.swing.JLabel(); jLabel2 = new javax.swing.JLabel(); src_phn = new javax.swing.JTextField(); src_result = new javax.swing.JButton(); result_box = new javax.swing.JTextField();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); src_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); jLabel1.setText("Name : ");

jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 
jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); jLabel2.setText(" Cell Nember: ");

src_phn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

src_result.setText("Show Result"); src_result.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) { src_resultActionPerformed(evt);
}
});

result_box.setEditable(false); result_box.setHorizontalAlignment(javax.swing.JTextField.CENTER); result_box.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) { result_boxActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane()); getContentPane().setLayout(layout);
layout.setHorizontalGroup( layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(56, 56, 56)

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(result_box, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(src_phn, javax.swing.GroupLayout.DEFAULT_SIZE, 363,
 
Short.MAX_VALUE)

Short.MAX_VALUE))))
 

.addComponent(src_name, javax.swing.GroupLayout.DEFAULT_SIZE, 363,
 
.addGroup(layout.createSequentialGroup()
.addGap(179, 179, 179)
.addComponent(jLabel2)))
.addGap(0, 71, Short.MAX_VALUE))
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(201, 201, 201)
.addComponent(jLabel1))
.addGroup(layout.createSequentialGroup()
.addGap(186, 186, 186)
.addComponent(src_result)))
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
);
layout.setVerticalGroup( layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
 
.addGap(18, 18, 18)
.addComponent(jLabel1)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(src_name, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(18, 18, 18)
.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(15, 15, 15)
.addComponent(src_phn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
.addComponent(src_result)
.addGap(31, 31, 31)
.addComponent(result_box, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(43, 43, 43))
);

pack();
}// </editor-fold>

private void result_boxActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void src_resultActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here: AddressBook s = new AddressBook(); if ((s.getName().equals(src_name))){
System.out.println("found");

}
}

/**
*	@param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
*	For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
{
if ("Nimbus".equals(info.getName())) { javax.swing.UIManager.setLookAndFeel(info.getClassName()); break;
}
 
}
} catch (ClassNotFoundException ex) { java.util.logging.Logger.getLogger(serc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) { java.util.logging.Logger.getLogger(serc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) { java.util.logging.Logger.getLogger(serc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) { java.util.logging.Logger.getLogger(serc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>

/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() { public void run() {
new serc().setVisible(true);
}
});
}

// Variables declaration - do not modify private javax.swing.JLabel jLabel1; private javax.swing.JLabel jLabel2; private javax.swing.JTextField result_box; private javax.swing.JTextField src_name; private javax.swing.JTextField src_phn; private javax.swing.JButton src_result;
// End of variables declaration
}

